module.exports = {
  'ADDPOINT':'#addPoint',
  'ADDREGION':'#addRegion',
  'BACK': '#back',
  'BACKWARD': '#backward',
  'CANVAS': '#openseadragon1',
  'COPY':'#copy',
  'DELETE':'#doDelete',
  'DELETEPOINT':'#deletePoint',
  'DRAW':'#draw',
  'DRAWLine':'#drawLine',
  'DRAWPOLYGON':'#drawPolygon',
  'FLIPREGION':'#flipRegion',
  'FOREWARD': '#foreward',
  'FRONT': '#front',
  'HOME':'#home',
  'MOVE': '#move',
  'NAVIGATE':  '#navigate',
  'NEXT':'.range-slider button:last-child',
  'PASTE':'#paste',
  'PREVIOUS':'.range-slider button:first-child',
  'REDO': '#redo',
  'ROTATE':'#rotate',
  'SAVE':'#save',
  'SCREENSHOT':'#screenshot',
  'SECTION':'#section',
  'SELECT':'#select',
  'SIMPLIFY':'#simplify',
  'SLIDER':'#slider',
  'SPLITREGION':'#splitRegion',
  'SUBTRACTREGION':'#subtractRegion',
  'TOBEZIER':'#toBezier',
  'TOPOLYGON':'#toPolygon',
  'UNDO':'#undo',
  'ZOOMIN':'#zoomIn',
  'ZOOMOUT':'#zoomOut'
};
